#!/usr/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <SYMBOL> <API_KEY>"
  exit 1
fi

SYMBOL="$1"
API_KEY="$2"

# 12 
API_URL="https://api.twelvedata.com/time_series?symbol=${SYMBOL}&interval=30min&apikey=${API_KEY}"

curl -X GET "$API_URL"
